10/hero
italanta/elewa-group pull request #100
Opened 2023-02-10 06:44 UTC by MildredKoskei

# Description

Created a responsive top page banner that shows the title, subtitle and an optional footer. It accepts this variables as an input and thus, they can all be modified by modifying the inputs

To achieve this, we did the following;
-Step 1: Create layout library inside the elements directory using the following command;
 `nx g @nrwl/angular:library elements/layout`

-Step 2: Create a components directory inside the layout/src/lib by `cd`-ing into it and running `mkdir` components

-Step 3: Create the elewa-hero component inside the components directory by using the command;
`nx g c elewa-hero`

-Step 4: Modify the contents of three files;
• elewa-hero.component.html
• elewa-hero.component.ts
• elewa-hero.component.scss
These files were created when we created the elewa-hero component

-Step 5: Commented out stuff on the file app.component.html and added a selector to our component <elewa-group-elewa-hero></elewa-group-elewa-hero> to test our work

Fixes # (issue 10)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Screenshot (optional)
![elewa-hero](https://user-images.githubusercontent.com/81473166/218018435-c0351623-0f22-4ab1-b71d-f747ee330c08.png)
# On a smaller screen
![elewa-hero-small-screen](https://user-images.githubusercontent.com/81473166/218020107-9bc39531-f367-4f27-b306-38049073c455.png)

# Video
[#issue10 video.webm](https://user-images.githubusercontent.com/81473166/218017526-6b2a306d-a45b-408b-9023-7a5e61ced1e8.webm)

# How Has This Been Tested?

Step 1: Commented out everything in the app.component.html and added a `elewa-group-elewa-hero` selector for our component
Step 2: Ran `nx serve elewa-group-website`
Step 3: Tested how the site would look on different devices using chrome developer tools.

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2023-02-10 07:59 UTC, IanOdhiambo9 requested changes
You've pushed your package-lock.json file.

Cannot be megerd

2023-02-10 07:59 UTC, IanOdhiambo9 commented on libs/elements/layout/src/lib/components/elewa-hero/elewa-hero.component.html
> +  <img class="backgroundImage" src="{{backgroundImg}}" alt="top banner hero image" />
use [src]="backgroundImg" instead of src="{{backgroundImg}}"

2023-02-10 07:59 UTC, IanOdhiambo9 commented on libs/elements/layout/src/lib/components/elewa-hero/elewa-hero.component.html
> +    <footer class="footer">{{ footer }}</footer>
This footer text is just a normal  "< p >" tag

2023-02-10 07:59 UTC, IanOdhiambo9 commented on apps/elewa-group-website/src/app/app.component.html
> +<!-- <elewa-group-header></elewa-group-header> -->
the home page should render here..

2023-02-10 08:21 UTC, MildredKoskei commented
we've made the changes please check the them out

2023-02-11 06:11 UTC, VinceXIV commented
We've solved the merge conflict. Please check @IanOdhiambo9

2023-02-13 05:49 UTC, IanOdhiambo9 requested changes
There's still a package-lock.json on this PR.
Please do a new PR without that file..

2023-02-13 05:50 UTC, IanOdhiambo9 commented
Closing because PR cannot be merged due to presence of package-lock.json file on the PR.

2023-02-13 05:50 UTC, closed without merging