12 create the home impact section
italanta/elewa-group pull request #102
Opened 2023-02-10 07:13 UTC by RajabKarume

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. 
List any dependencies that are required for this change.

Example
This pull request is part of the work to make it easier for people to contribute to naming convention guides. 
One of the easiest way to make small changes would be using the Edit on Github button.

To achieve this, we needed to:

```
- Find the best Gitbook plugin which can do the work
- Integrate it in all the pages to redirect the user to the right page on GitHub for editing
- Make it visible on the page so users can notice it easily
```

Fixes # (issue) - *Example*: Fixes # ([S4Y-400](https://www.w3.org/Provider/Style/dummy.html), [S4Y-100](https://www.w3.org/Provider/Style/dummy.html))

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

# Screenshot (optional)

![Screenshot from 2023-02-10 09-57-31](https://user-images.githubusercontent.com/109956415/218026333-ac933786-7d54-47b4-a2c7-1a505fb19d87.png)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 
Please also list any relevant details for your test configuration if necessary.
- [ ] Test A
- [ ] Test B

**Test Configuration**: (optional)
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:
- [✅ ] My code follows the style guidelines of this project
- [✅ ] I have performed a self-review of my code
- [ ✅] I have commented my code, particularly in hard-to-understand areas
- [ ✅] I have made corresponding changes to the documentation
- [ ✅] My changes generate no new warnings
- [ ✅] I have added tests that prove my fix is effective or that my feature works
- [✅ ] New and existing unit tests pass locally with my changes
- [✅ ] Any dependent changes have been merged and published in downstream modules

2023-02-10 08:01 UTC, IanOdhiambo9 commented
Do a proper description highlighting the issue you're working on e.t.c..

2023-02-10 08:03 UTC, IanOdhiambo9 requested changes
Update the description for this PR

2023-02-10 08:43 UTC, RajabKarume commented
📝doc: updated description of the PR

2023-02-13 05:59 UTC, IanOdhiambo9 requested changes
Add a screenshot for mobile as well.

2023-02-13 05:59 UTC, IanOdhiambo9 commented on apps/elewa-group-website/src/app/app.routing.ts
> +
This route needs to go to the home module and have a default path to the HomePageComponent.

However, routing was not a concern of this issue

2023-02-13 05:59 UTC, IanOdhiambo9 commented on libs/pages/elewa/home/src/lib/components/home-impact-section/home-impact-section.component.ts
> +  Our group owned and managed by our founder, our employees (across our brands) and our network of 56 passionate angel investors.`
This is not a reusable component, hence no need for inputs.

2023-02-13 05:59 UTC, IanOdhiambo9 commented on libs/pages/elewa/home/src/lib/features-elewa-home.module.ts
>  })
No need to export HomeImpactSectionComponent since it's not reused anywhere

2023-02-13 05:59 UTC, IanOdhiambo9 commented on libs/pages/elewa/home/src/lib/pages/home-page/home-page.component.html
> +  <elewa-group-home-impact-section></elewa-group-home-impact-section>
Good 👍🏾

2023-02-13 05:59 UTC, IanOdhiambo9 commented on tsconfig.base.json
> -      "@elewa-group/features/components/cards": ["libs/features/components/cards/src/index.ts"],
This are important project package files, cannot be removed.

2023-02-13 06:00 UTC, IanOdhiambo9 commented
Resolve conflicts on this branch.

2023-02-14 06:04 UTC, IanOdhiambo9 commented
Check the mobile design, everything is centered and buttons equal width.

2023-02-17 07:52 UTC, IanOdhiambo9 requested changes

2023-02-17 07:52 UTC, IanOdhiambo9 commented on libs/pages/elewa/home/src/lib/components/home-impact-section/home-impact-section.component.scss
> +    .button {
format this file better.

2023-02-17 07:53 UTC, IanOdhiambo9 commented
Center the text on the button, as shown on the design so we can close this.

2023-02-21 08:56 UTC, LemmyMwaura commented
This is close to being completed. Make the necessary changes so we can approve.

2023-02-21 09:12 UTC, RajabKarume commented
> This is close to being completed. Make the necessary changes so we can approve.

Could you please give me more information on the changes I need to make?

2023-02-21 09:30 UTC, LemmyMwaura commented
> > This is close to being completed. Make the necessary changes so we can approve.
> 
> Could you please give me more information on the changes I need to make?

That has been provided above.

2023-02-21 11:04 UTC, RajabKarume commented
Changes requested have been made

2023-02-22 08:18 UTC, IanOdhiambo9 approved these changes

2023-02-22 08:18 UTC, merged

2023-02-22 08:31 UTC, IanOdhiambo9 commented
I've reverted this Merge because after checking I've noticed your work still has a number of issues.
<img width="1440" alt="Screenshot 2023-02-22 at 11 21 32" src="https://user-images.githubusercontent.com/29625264/220564864-1a6b6370-1290-438e-aac0-deead9278a48.png">

When you hover on one button, both buttons animations are triggered.
The right margin does not exist on laptop viewport

2023-02-22 08:32 UTC, IanOdhiambo9 commented
The font size is also far too big