38
italanta/elewa-group pull request #115
Opened 2023-02-10 08:52 UTC by Dcolonel6

# Description

This pull request is part creating a reusable partner orgs section. We worked on this with @nziokikevin

Example
This pull request is part of the work to make it easier for people to contribute to naming convention guides. 
One of the easiest way to make small changes would be using the Edit on Github button.

To achieve this, we needed to:

```
- Find the best Gitbook plugin which can do the work
- Integrate it in all the pages to redirect the user to the right page on GitHub for editing
- Make it visible on the page so users can notice it easily
```

Fixes # 38 - *Create Reusable Partner Orgs Section*: [Fixes # 38](https://github.com/italanta/elewa-group/issues/38)
## Type of change
- [X] New feature (non-breaking change which adds functionality)

# Screenshoots

## Large screens
![Screenshot from 2023-02-10 11-38-17](https://user-images.githubusercontent.com/11848689/218043773-aa179069-a7ce-4cc1-b906-6bae4512e9a2.png)

## Mobile Screen
![Screenshot from 2023-02-10 11-42-01](https://user-images.githubusercontent.com/11848689/218044492-b147da4a-2ab9-467d-afa7-80d470c86caa.png)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 
Please also list any relevant details for your test configuration if necessary.
- [x] Test A
- [X] Test B

# Checklist:
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

2023-02-10 08:53 UTC, Dcolonel6 commented
Please review @IanOdhiambo9

2023-02-13 07:05 UTC, IanOdhiambo9 requested changes
Elewa group button is not part of this issue. sync fork.

2023-02-13 07:05 UTC, IanOdhiambo9 commented on apps/elewa-group-website/src/app/app.component.html
> +<elewa-group-elewa-group-horizontal-list-orgs></elewa-group-elewa-group-horizontal-list-orgs>
Only the homepage should be here, remove your tag after local testing

2023-02-13 07:05 UTC, IanOdhiambo9 commented on apps/elewa-group-website/src/app/app.module.ts
Not needed here

2023-02-13 07:05 UTC, IanOdhiambo9 commented on libs/features/components/buttons/project.json
> +          "libs/features/components/buttons/**/*.html"
This is not part of this issue

2023-02-13 07:05 UTC, IanOdhiambo9 commented on libs/features/components/ui-lists/src/lib/components/elewa-group-horizontal-list-orgs/elewa-group-horizontal-list-orgs.component.html
> +</ul>
Make the logos a pair of two on each row in the mobile view.

2023-02-13 07:05 UTC, IanOdhiambo9 commented on libs/features/components/ui-lists/src/lib/components/elewa-group-horizontal-list-orgs/elewa-group-horizontal-list-orgs.component.ts
> +        "https://rwanda.vvob.org/sites/rwanda/files/styles/780pxx330px/public/images/mainimagebig/ok.jpg?itok=zMR2_g-z 720w"
The logos will be relatively small in size, just use a list of urls instead.

2023-02-13 07:07 UTC, IanOdhiambo9 commented
Resolve conflicts on branch

2023-02-14 10:18 UTC, closed without merging