10/reusable hero
italanta/elewa-group pull request #134
Opened 2023-02-11 00:22 UTC by NewtonOmbese

# Description

This pull request is for the Reusable Hero Section issue. This issue is depended upon by other issues hence a reusable component it is. 

To achieve this, we needed to:

```
- Create the component in the articulated path
- Create an exact duplicate of the design provided
- Needed to write a ngIf statement for the footer text
```

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

# Screenshot (optional)
![Screenshot from 2023-02-11 03-01-30](https://user-images.githubusercontent.com/79839603/218225766-c39e0e17-f8db-47c4-8c71-0bd44ed597b0.png)

# Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-02-11 00:23 UTC, NewtonOmbese commented
Review and give feedback @IanOdhiambo9

2023-02-13 08:58 UTC, IanOdhiambo9 requested changes
Provide screenshot for mobile view

2023-02-13 08:58 UTC, IanOdhiambo9 commented on tsconfig.base.json
>        "@elewa-group/state/data/cms": ["libs/state/data/cms/src/index.ts"],
cards component is needed here as well. please retain it too

2023-02-13 09:16 UTC, NewtonOmbese commented
![Screenshot from 2023-02-13 12-14-57](https://user-images.githubusercontent.com/79839603/218417925-75eeaf38-a773-4630-bf1d-3b58eaf68239.png)

Mobile view

2023-02-13 09:16 UTC, NewtonOmbese commented
Mobile view screenshot provided @IanOdhiambo9

2023-02-14 07:56 UTC, NewtonOmbese commented
Review and give feedback @IanOdhiambo9

2023-02-14 09:40 UTC, IanOdhiambo9 commented
Closing PR due to conflicts and issue status being closed.
Review feedback and apply on the next issue.

2023-02-14 09:40 UTC, closed without merging