#20 about us location section
italanta/elewa-group pull request #146
Opened 2023-02-13 10:08 UTC by adamswonder

### About us location section [⚡#20](#20)

# Summary

This feature shows the physical location of the organization and a link to get directions using angular google maps. It makes it easier for one to effectively map out the organization's address using geolocation.

To achieve this, we needed to:

```
- Find the best map API/service which would help pinpoint the organization's precise location
- Apply for an API_KEY and Integrate it in the page section to give the location and/or directions
- Provide a marker making it visible on the page section so users can notice it easily
```
```
- Used an Image placeholder for the map

`<div class="location-main-flex">

  <div class="map">
    
    
    <img style="height:'400px';width:'400px'"
      src="https://i.postimg.cc/hPR51tsr/Screenshot-from-2023-02-11-11-46-03.png"
    />
  </div>
...`

```

Fixes [#20 ]

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Overview
## Screenshot
![desktop](https://user-images.githubusercontent.com/108331299/218425683-9a69da2d-a9da-4c2a-8391-728f55e69c84.jpeg)
![mobile](https://user-images.githubusercontent.com/108331299/218425710-427de479-74b1-49a9-beca-3caea00a1527.jpeg)

## Live Demo

https://user-images.githubusercontent.com/108331299/218426189-bbc35223-fea1-4dbd-9867-4c0e48df6540.mp4

# Checklist:
- [x] Our code follows the style guidelines of this project
- [x] We have performed a self-review of our code
- [x] We have commented on our code, particularly in hard-to-understand areas
- [x] Our changes generate no new warnings

2023-02-13 10:52 UTC, JamesMGithire reviewed
Code changes are okay🚀

2023-02-13 11:31 UTC, IanOdhiambo9 requested changes
You need to add a marker on the map with the provided Geo-points

2023-02-13 11:31 UTC, IanOdhiambo9 commented on libs/pages/elewa/about-us/src/lib/components/elewa-about-us-location-section/elewa-about-us-location-section.component.css
> +
This should be a .scss file not css

2023-02-13 11:31 UTC, IanOdhiambo9 commented on libs/pages/elewa/about-us/src/lib/components/elewa-about-us-location-section/elewa-about-us-location-section.component.ts
> +      this.center = {
Lat and long points for ELewa location

-1.256132162858307, 36.80501589843353

2023-02-13 13:01 UTC, JamesMGithire reviewed
Completed chaneges.

2023-02-17 07:22 UTC, IanOdhiambo9 approved these changes

2023-02-17 07:22 UTC, merged