#32 social impact cooperative section
italanta/elewa-group pull request #189
Opened 2023-02-16 07:41 UTC by Eddahkarambu

# [#32 ] Social Impact Cooperative Section 

<p> This is a section that describes the organizations' common objectives </p>

## Changes 
<p> The component displays by reusing the banners feature from <em>#31</em>

## Desktop Preview 
![WhatsApp Image 2023-02-16 at 10 28 43 (1)](https://user-images.githubusercontent.com/85109484/219298837-d71ae138-555c-4c3c-8df6-8328d03dd3bd.jpeg)

## Mobile Preview 
![WhatsApp Image 2023-02-16 at 10 28 43](https://user-images.githubusercontent.com/85109484/219298929-ed8bac86-8a25-4719-becd-3391de4a57b0.jpeg)

## Contributors 
<h2> Code was written by @Essyuge ,  @JohnstoneDev & I . 

<h4> @IanOdhiambo9 Kindly Review. </h4>

2023-02-21 10:05 UTC, LemmyMwaura requested changes
Rename social impact to cooperative section and move it into a components folder. Really clean design. Good job so far 👍

2023-02-21 10:05 UTC, LemmyMwaura commented on libs/pages/elewa/home/src/lib/features-elewa-home.module.ts
> +  // exports: [HomePageComponent, HomeHeroSectionComponent, HomeJobsSectionComponent, TeamAndPartnersComponent, ActivitySectionComponent, NextDirective, PrevDirective],
?? duplication

2023-02-21 10:05 UTC, LemmyMwaura commented on libs/pages/elewa/home/src/lib/social-impact/social-impact.component.html
> +<elewa-group-elewa-group-image-and-text-banner
this should be in a components folder

2023-02-21 13:35 UTC, Eddahkarambu commented
@LemmyMwaura Kindly review.

2023-02-22 08:47 UTC, IanOdhiambo9 commented
I'm closing this PR because it contains package.json and package-lock.json files.

Please do a New PR without this files.

2023-02-22 08:47 UTC, closed without merging