Social impact
italanta/elewa-group pull request #191
Opened 2023-02-16 08:26 UTC by Michael-Otieno

# Description

Worked alone.

This pull request solves issue #19, whereby we have created a responsive About us page (We care) section following the design's guidelines.

Fixes #19

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# Screenshot (optional)

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2023-02-21 11:40 UTC, LemmyMwaura requested changes
Link a video or screenshot for both mobile and desktop showing the updates you made

2023-02-21 11:42 UTC, LemmyMwaura commented on libs/pages/elewa/home/src/lib/features-elewa-home.module.ts
> +import {PagesElewaSocialImpactModule} from '@elewa-group/pages/elewa/social-impact';
Order of imports

2023-02-21 14:40 UTC, Michael-Otieno commented on libs/pages/elewa/home/src/lib/features-elewa-home.module.ts
> +import {PagesElewaSocialImpactModule} from '@elewa-group/pages/elewa/social-impact';
what's the issue? I don't understand

2023-02-21 17:14 UTC, LemmyMwaura commented on libs/pages/elewa/home/src/lib/features-elewa-home.module.ts
> +import {PagesElewaSocialImpactModule} from '@elewa-group/pages/elewa/social-impact';
fix the order of imports.

2023-02-22 09:04 UTC, IanOdhiambo9 commented on libs/pages/elewa/social-impact/src/lib/social-impact/social-impact.component.html
> +<elewa-group-footer></elewa-group-footer>
footer should only be on the main page

2023-02-22 09:04 UTC, IanOdhiambo9 reviewed
Closing PR due to conflicts and issue on hold

2023-02-22 09:08 UTC, IanOdhiambo9 commented
Please check issue #252 for footer implementation

2023-02-22 09:08 UTC, closed without merging