34 social impact
italanta/elewa-group pull request #197
Opened 2023-02-16 09:46 UTC by nziokikevin

# Description

Created a section that describes the organisation open knowledge that shows an image on the right side, a paragraph of text and a title. This component displays provided text and images side by side on the social impact section using the reusable component in issue #31.

To achieve this, we needed to:
- Step 1: Created social-impact library inside the pages directory using:
```
nx g @nrwl/angular:library pages/elewa/social-impact
```
- Step 2: Created a components folder inside libs/pages/elewa/social-impact/src/lib.
- Step 3: Created social-impact component inside the components folder using:
```
nx g c social-impact
```

Fixes # (issue 34)

## Type of change

Please delete options that are not relevant.
- [X] New feature (non-breaking change which adds functionality)

# Screenshot (optional)
For desktop
![Screenshot from 2023-02-16 11-51-42](https://user-images.githubusercontent.com/106156182/219327390-a5878298-858a-49a2-9e3a-e0b0546ae41a.png)

For Mobile
![Screenshot from 2023-02-16 11-52-00](https://user-images.githubusercontent.com/106156182/219327555-8526908f-b098-4310-a846-8168cd237125.png)

# How Has This Been Tested?
Step 1: Commented out everything in app.component.html and did the required imports and exports.
Step 2: Ran ```nx serve elewa-group-website```
Step 3: Tested how the website's responsiveness using chrome developer tools.

# Checklist:
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-02-16 09:47 UTC, nziokikevin commented
Please review and give feedback @IanOdhiambo9

2023-02-21 12:18 UTC, LemmyMwaura requested changes
This library was already generated. Sync with the latest changes and work from there. but good job so far.

2023-02-22 09:11 UTC, IanOdhiambo9 requested changes

2023-02-22 09:11 UTC, IanOdhiambo9 commented on libs/pages/elewa/social-impact/src/lib/components/social-impact/social-impact.component.html
> +[paragraphText]="paragraphText"
This is now an array, take note of update and. sync fork

2023-02-23 05:52 UTC, closed without merging