#4/elewa home lander
italanta/elewa-group pull request #201
Opened 2023-02-16 12:05 UTC by littlephillips

# Description

This pull request is a feature creation for the elewa home page lander component. 
We worked with [@Anna-Ashton](https://github.com/Anna-Ashton)  and [@chegeian](https://github.com/chegeian)

To achieve this, we needed to:

```
- Create a standalone component 
- re-using elewa hero component
- add relevant text for the page rendered
```

Fixes issue [#4 ](https://github.com/italanta/elewa-group/issues/4)

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

# Screenshot (optional)

![home-lander](https://user-images.githubusercontent.com/106226164/219359900-76722634-45d6-4bfa-b634-4c20b8fc6c03.png)
![home0lander-mobile](https://user-images.githubusercontent.com/106226164/219359920-b0f7cf55-0605-426b-8fd2-72243735d83c.png)

# Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

2023-02-16 12:05 UTC, littlephillips commented
kindly review @IanOdhiambo9

2023-02-21 18:44 UTC, LemmyMwaura requested changes
Good job on the design, though mobile can be improved. Reuse the dynamic hero component that was already created.

2023-02-21 18:44 UTC, LemmyMwaura commented on libs/pages/elewa/home/src/lib/components/home-lander-section/home-lander-section.component.html
> +<elewa-group-elewa-hero
You're supposed to reuse the dynamic hero component that's already created and pass the correct attributes as inputs.

2023-02-22 09:18 UTC, IanOdhiambo9 commented
This issue has been closed.

2023-02-22 09:18 UTC, closed without merging