#4 : Create the home page lander
italanta/elewa-group pull request #209
Opened 2023-02-16 20:11 UTC by Dcolonel6

# Description
 Create the home page lander that captures user attention and gives a good experience on the phone and web

To achieve this, we needed to:

```
- As a user I want a nice home page that captures my attention.
- I want a good experience on web and phone
```

Fixes # (4) -  [Fixes #4 Create the home page lander:](https://github.com/italanta/elewa-group/issues/4)

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# Screenshot 

## Web
![Screen Shot 2023-02-16 at 22 56 27](https://user-images.githubusercontent.com/11848689/219475426-fc67cda8-696a-41e2-9f1a-d14337eeaf91.png)

## Mobile
![Screen Shot 2023-02-16 at 22 54 58](https://user-images.githubusercontent.com/11848689/219475541-dfb94426-e19b-4778-8463-c0dc01a47370.png)

# Checklist:
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] Any dependent changes have been merged and published in downstream modules

2023-02-17 07:46 UTC, IanOdhiambo9 requested changes

2023-02-17 07:46 UTC, IanOdhiambo9 commented on libs/pages/elewa/home/src/lib/components/elewa-home-page-lander/elewa-home-page-lander.component.html
> +</elewa-group-elewa-hero>
The hero should be on the home page, not a separate component.

2023-02-17 07:46 UTC, IanOdhiambo9 commented on libs/pages/elewa/home/src/lib/features-elewa-home.module.ts
> +    ElewaHomePageLanderComponent,
No need to have this component..

2023-02-17 08:36 UTC, Dcolonel6 commented
@IanOdhiambo9  changes have been effected

2023-02-22 05:52 UTC, LemmyMwaura approved these changes
Good job.

2023-02-22 09:15 UTC, IanOdhiambo9 commented
This issue has been merged, left margin has been fixed in issue as per design.

2023-02-22 09:15 UTC, closed without merging