Social impact
italanta/elewa-group pull request #210
Opened 2023-02-16 21:03 UTC by Bel-94

This pull request is part of the work on issue #34 done in collaboration with @pauline123

To achieve this, we needed to:

```
- to re-use the banner component #31
- import the BannerModule so that we can re-use the component
- Make it pixel perfect and mobile friendly
```

Fixes #34 

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

# Screenshot
Social impact open knowledge with image on the right
![Screenshot from 2023-02-16 23-38-18](https://user-images.githubusercontent.com/100135405/219481633-1a4a1f5d-509e-461b-a9e0-e115cf083f16.png)

Social impact open knowledge mobile version
![Screenshot from 2023-02-16 23-59-15](https://user-images.githubusercontent.com/100135405/219485520-3f2425f7-7577-49a2-af71-2aa665a0eac9.png)

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

2023-02-16 21:06 UTC, Bel-94 commented
Hello @IanOdhiambo9 kindly review my PR #210

2023-02-22 06:13 UTC, LemmyMwaura requested changes
Sync with the latest updates and work from there.

2023-02-22 06:13 UTC, LemmyMwaura commented on libs/features/components/cards/src/lib/pages/elewa-group-card/elewa-group-card.component.html
> +<div class="row row-cols-1 row-cols-md-3 g-4">
This should not be in a pages folder as it's not a page, also the card is already present. Please sync with the latest changes and work from there.

2023-02-22 06:13 UTC, LemmyMwaura commented on libs/pages/elewa/home/src/lib/pages/home-page/home-page.component.html
> +>>>>>>> 1f5124ccd6a27958b4d7e74ec6e9dd4b5b85ce42
?? remove

2023-02-22 06:13 UTC, LemmyMwaura commented on libs/pages/elewa/home/src/lib/pages/home-page/home-page.component.html
> +=======
remove

2023-02-22 06:13 UTC, LemmyMwaura commented on libs/pages/elewa/social-impact/src/lib/pages-elewa-social-impact.module.ts
> +import { SocialImpactPageComponent } from './pages/social-impact-page/social-impact-page.component';
fix order of imports

2023-02-22 09:23 UTC, IanOdhiambo9 commented
Too many files changed for this issue. Sync and resolve conflicts then reopen after changes implemented.

2023-02-22 09:23 UTC, closed without merging