30/people section
italanta/elewa-group pull request #213
Opened 2023-02-17 07:00 UTC by George-Onyango

# Description

This is a pull request that fixes issue 30 creating the counter of investor and careers started

Fixes # (issue) - (#30 )

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# Screenshot (optional)
![Screenshot from 2023-02-17 09-59-17](https://user-images.githubusercontent.com/69570282/219572227-e3d268b7-b171-4317-91a4-1d95f5b7bca9.png)

Mobile
![Screenshot from 2023-02-17 09-59-10](https://user-images.githubusercontent.com/69570282/219572266-f4c3c6e8-a7d3-4ca1-a389-5e8f6e19897c.png)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 
Please also list any relevant details for your test configuration if necessary.
- [x] Test against responsive screen 

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2023-02-17 07:01 UTC, George-Onyango commented
@IanOdhiambo9 requesting review

2023-02-22 07:16 UTC, LemmyMwaura requested changes
Design does not match the expectation. Please put some effort on your design.

2023-02-22 07:16 UTC, LemmyMwaura commented on libs/pages/elewa/social-impact/src/lib/pages-elewa-social-impact.module.ts
>  import { SocialImpactRoutingModule } from './social-impact.routing';
Routing Module comes last

2023-02-22 07:16 UTC, LemmyMwaura commented on libs/pages/elewa/social-impact/tsconfig.lib.json
> +  // "include": ["src/**/*.ts"]
remove this

2023-02-22 08:23 UTC, LemmyMwaura commented on libs/pages/elewa/social-impact/src/lib/pages-elewa-social-impact.module.ts
> +import { ElewaGroupImageAndTextBannerComponent } from 'libs/features/components/banners/src/lib/banners/elewa-group-image-and-text-banner/elewa-group-image-and-text-banner.component';
import from the aliased path.

2023-02-22 12:24 UTC, IanOdhiambo9 requested changes
I can't see the image and text banner in the screenshots

2023-02-22 13:54 UTC, IanOdhiambo9 commented
I'm closing PR because this issue has been closed

2023-02-22 13:54 UTC, closed without merging