Issue30/ft social impact section
italanta/elewa-group pull request #218
Opened 2023-02-17 08:54 UTC by Beulah-Matt

# Description
This pull request is for people to see the impact of elewa group
Made a people's section with animated statistics increasing evenly in about 5 seconds

To achieve this, we needed to:

```
- Make a header showing the current numbers
- Improve the UI by allowing for animation as numbers increased on page load.
- Make it visible on the page so users can notice it easily
```

Fixes # [(issue) - [*Example*: Fixes # ([S4Y-400](https://www.w3.org/Provider/Style/dummy.html), [S4Y-100](https://www.w3.org/Provider/Style/dummy.html))](https://github.com/italanta/elewa-group/issues/30)](https://github.com/italanta/elewa-group/issues/30)

## Type of change
- [ ] New feature (non-breaking change which adds functionality)

# Scree
![mobile](https://user-images.githubusercontent.com/109944021/219573328-5fc93a95-2584-496c-98ba-2383a3396824.png)
nshot 

![fullscreen](https://user-images.githubusercontent.com/109944021/219573384-4ddb5b2c-c16a-4cb1-bb66-2bcdd6f0fcdf.png)

# How Has This Been Tested?

I inspected the component for both full view and on mobile view with a media query of max 600px

# Checklist:
- [yes ] My code follows the style guidelines of this project
- [yes ] My changes generate no new warnings
- [ yes] New and existing unit tests pass locally with my changes

2023-02-17 08:55 UTC, Beulah-Matt commented
@IanOdhiambo9 kindly review this request.

2023-02-22 07:56 UTC, LemmyMwaura requested changes
Looks good as of now 👍 . Please link a video showing how the increment works.

2023-02-22 07:57 UTC, LemmyMwaura commented on libs/pages/elewa/social-impact/src/lib/pages-elewa-social-impact.module.ts
>  import { SocialImpactRoutingModule } from './social-impact.routing';
RoutingModule import comes last, move this to the end.

2023-02-22 07:58 UTC, LemmyMwaura commented on libs/pages/elewa/social-impact/src/lib/pages-elewa-social-impact.module.ts
> +import { ElewaGroupImageAndTextBannerComponent } from 'libs/features/components/banners/src/lib/banners/elewa-group-image-and-text-banner/elewa-group-image-and-text-banner.component';
RoutingModule import comes last, move this to the end.

2023-02-22 08:24 UTC, LemmyMwaura commented on libs/pages/elewa/social-impact/src/lib/pages-elewa-social-impact.module.ts
> +import { ElewaGroupImageAndTextBannerComponent } from 'libs/features/components/banners/src/lib/banners/elewa-group-image-and-text-banner/elewa-group-image-and-text-banner.component';
Import from the aliased path

2023-02-22 13:31 UTC, closed without merging