Beyond business
italanta/elewa-group pull request #219
Opened 2023-02-17 09:12 UTC by Bel-94

This pull request is part of the work on issue #33  done in collaboration with.

To achieve this, we needed to:

```
- to re-use the banner component #31
- import the BannerModule so that we can re-use the component
- Make it pixel perfect and mobile friendly
```

Fixes #33  

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

# Screenshot
Social impact beyond business with image on the left
![Screenshot from 2023-02-17 12-06-28](https://user-images.githubusercontent.com/100135405/219602154-32bce3cc-1113-4704-b693-892e59819edc.png)

Social impact beyond business with image on the left mobile version
![Screenshot from 2023-02-17 11-39-24](https://user-images.githubusercontent.com/100135405/219602218-fef58c13-a6c7-400d-bc2e-445e067d4abf.png)

![Screenshot from 2023-02-17 11-40-03](https://user-images.githubusercontent.com/100135405/219602278-bec4bcb2-068c-44a6-991d-cdde1b842962.png)

![Screenshot from 2023-02-17 11-40-22](https://user-images.githubusercontent.com/100135405/219602365-ef6dba9b-93c5-4872-82d3-b3cb7fb7d91e.png)

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

2023-02-17 09:16 UTC, Bel-94 commented
Hi @IanOdhiambo9 kindly review my PR #219

2023-02-22 08:40 UTC, LemmyMwaura requested changes
Sync with the latest updates as the social impact lib was already created and work from there

2023-02-22 08:40 UTC, LemmyMwaura commented on libs/pages/elewa/home/src/lib/pages/home-page/home-page.component.html
> +=======
remove this

2023-02-22 08:40 UTC, LemmyMwaura commented on libs/pages/elewa/home/src/lib/pages/home-page/home-page.component.html
> +>>>>>>> 1f5124ccd6a27958b4d7e74ec6e9dd4b5b85ce42
remove

2023-02-22 08:40 UTC, LemmyMwaura commented on libs/pages/elewa/home/src/lib/pages/home-page/home-page.component.html
> +<<<<<<< HEAD
remove

2023-02-22 08:40 UTC, LemmyMwaura commented on libs/pages/elewa/home/src/lib/pages/home-page/home-page.component.html
> +<div class="home-page">
This should not be in a pages folder as it's not a page.

2023-02-22 11:18 UTC, IanOdhiambo9 requested changes
This is too many files changed for this issue.
Please sync fork and resolve conflicts then reopen PR after changed implemented

2023-02-22 11:18 UTC, closed without merging