33/social impact beyond business section
italanta/elewa-group pull request #220
Opened 2023-02-17 09:23 UTC by NewtonOmbese

# Description

Created a section that describes the Social Impact beyond business section that shows an image on the right side, a paragraph of text and a title. This component displays provided text and images side by side on the social impact section using the reusable animated button components in issue https://github.com/italanta/elewa-group/issues/31. 

To achieve this, I needed to:
- Step 1: Create the home impact section component
```
nx g @nrwl/angular:component pages/elewa/social-impact
```
- Make an import of the button module to be reused in the component

Fixes # (issue  https://github.com/italanta/elewa-group/issues/33) 

## Type of change
- [ ] New feature (non-breaking change which adds functionality)

# Screenshot (optional)
Desktop View
![beyond-business-desktop](https://user-images.githubusercontent.com/79839603/219604782-dc69eed6-ade8-41cd-8a81-c9c961d35fe4.png)

Mobile View
![beyond-business-mobile](https://user-images.githubusercontent.com/79839603/219604817-1caa7f6a-545b-453a-a877-5a5b3fdb8e72.png)

# How Has This Been Tested?
Step 1: Added the component to social-impact-page.component.html
Step 2: Started the server by running ```nx serve elewa-group-website```
Step 3: Using chrome developer tools to test on the responsiveness of the website

# Checklist:t
- [ ] I have performed a self-review of my code
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-02-17 09:23 UTC, NewtonOmbese commented
Review and merge @IanOdhiambo9

2023-02-22 07:04 UTC, NewtonOmbese commented
Updated the Paragraphs as they were declared as arrays
Review and Merge @IanOdhiambo9

2023-02-22 09:00 UTC, LemmyMwaura commented on libs/pages/elewa/social-impact/src/lib/pages-elewa-social-impact.module.ts
> +import { BannersModule } from '@elewa-group/features/components/banners';
Fix the order of imports

2023-02-22 09:09 UTC, LemmyMwaura requested changes
Fix the imports

2023-02-22 09:09 UTC, LemmyMwaura commented on libs/pages/elewa/social-impact/src/lib/pages-elewa-social-impact.module.ts
> +import { BannersModule } from '@elewa-group/features/components/banners';
Fix the order of imports

2023-02-22 09:27 UTC, NewtonOmbese commented
@LemmyMwaura done fixing the order

2023-02-22 14:33 UTC, NewtonOmbese commented
@LemmyMwaura  new issue fix review and give feedback

2023-02-23 06:30 UTC, LemmyMwaura requested changes
Looks good, Sync the latest updates

2023-02-23 08:12 UTC, NewtonOmbese commented
Done syncing

2023-02-24 05:48 UTC, IanOdhiambo9 commented
Closing this because newton can't work on one points anymore, but good job!

2023-02-24 05:48 UTC, closed without merging