33 social impact beyond business section
italanta/elewa-group pull request #226
Opened 2023-02-17 11:45 UTC by RajabKarume

# Description

This pull request is part of the work to make it easier for people to view a section that described the organization beyond business

To achieve this, we needed to:

```
- Create a beyond business component
- Add the correct inputs for the title, paragraph, and image
```

Fixes [#33](https://github.com/italanta/elewa-group/issues/33)

## Type of change

Please delete options that are not relevant.

- [✅] New feature (non-breaking change which adds functionality)

# Screenshot (optional)

![Screenshot from 2023-02-17 14-17-10](https://user-images.githubusercontent.com/109956415/219644435-31a06097-c6f7-4f92-b25b-2cf57512cb9c.png)

![Screenshot from 2023-02-17 14-17-45](https://user-images.githubusercontent.com/109956415/219644502-0971c26f-a82e-4462-84c2-3d8d6c3f9356.png)

# Checklist:
- [✅] My code follows the style guidelines of this project
- [✅] I have performed a self-review of my code
- [✅] I have commented my code, particularly in hard-to-understand areas
- [✅] I have made corresponding changes to the documentation
- [✅] My changes generate no new warnings
- [✅] I have added tests that prove my fix is effective or that my feature works
- [✅] New and existing unit tests pass locally with my changes
- [✅] Any dependent changes have been merged and published in downstream modules

2023-02-22 09:48 UTC, LemmyMwaura requested changes

2023-02-22 09:48 UTC, LemmyMwaura commented on libs/pages/elewa/social-impact/src/lib/pages-elewa-social-impact.module.ts
> +import { BannersModule } from '@elewa-group/features/components/banners';
Order of imports

2023-02-23 05:26 UTC, IanOdhiambo9 requested changes
This section has a white background please pass the background color as part of the input properties for this component

2023-02-23 05:26 UTC, IanOdhiambo9 commented on libs/pages/elewa/social-impact/src/lib/pages/social-impact-page/social-impact-page.component.html
> +<elewa-group-beyond-business></elewa-group-beyond-business>
You're missing some updates from your peers on this file, please sync

2023-02-23 07:27 UTC, LemmyMwaura commented on libs/pages/elewa/social-impact/src/lib/pages/components/beyond-business/beyond-business.component.html
> +[paragraphTexts]="['Some of that youthful energy is channeled beyond business. Through projects such as our coding school in Kakuma refugee camp, training teachers in pastoral Samburu and our open-so
Challenge. Set the values as properties in your component and bind to that instead.

2023-02-23 07:28 UTC, LemmyMwaura requested changes

2023-02-23 07:28 UTC, LemmyMwaura commented on libs/pages/elewa/social-impact/src/lib/pages/components/beyond-business/beyond-business.component.html
> +[paragraphTexts]="['Some of that youthful energy is channeled beyond business. Through projects such as our coding school in Kakuma refugee camp, training teachers in pastoral Samburu and our open-so
Challenge. Set the values as properties in your component and bind to that instead.

2023-02-23 07:39 UTC, LemmyMwaura commented
The elewa image banner is not imported and also set the values being passed to it as properties

2023-02-24 05:49 UTC, IanOdhiambo9 approved these changes

2023-02-24 05:50 UTC, merged