19/aboutuspage we care section
italanta/elewa-group pull request #265
Opened 2023-02-22 13:52 UTC by init-commit

# Description

This pull request is for issue #19 and aims at creating the About Us page(we care section). We have worked in this issue with [Jane Wandia](https://github.com/Jane-Wandia).

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

# Screenshot (optional)

![wecare-whole](https://user-images.githubusercontent.com/108511481/220627638-8c607e00-94e0-4304-a9a5-53a03261ac78.png)
![wecare-responsive-1](https://user-images.githubusercontent.com/108511481/220627676-bbd551a8-edaa-4cfb-9f72-8bdf4d957262.png)
![wecare-responsive-2](https://user-images.githubusercontent.com/108511481/220627720-51bdb21b-fb12-41a5-b3b4-7917d9729f3c.png)

# Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

@IanOdhiambo9  Awaiting your review.

2023-02-23 12:26 UTC, LemmyMwaura requested changes
Make the necessary updates

2023-02-23 12:26 UTC, LemmyMwaura commented on libs/pages/elewa/about-us/src/lib/elewa-about-us.module.ts
> +import { CardsModule } from '@elewa-group/features/components/cards';
fix the order of imports, This should be at the domain level above all components/directive imports

2023-02-23 12:26 UTC, LemmyMwaura commented on libs/pages/elewa/about-us/src/lib/elewa-about-us.module.ts
> +  exports: [TeamMembersCarouselComponent, ElewaAboutUsLocationSectionComponent, AboutUsWeCareComponent, ElewaVerticalIconAndTextComponent],
No need to export the component you created and the verticalIconandtext component does not belong to this module so it should not be exported.

2023-02-23 12:29 UTC, LemmyMwaura commented on libs/pages/elewa/about-us/src/lib/elewa-about-us.module.ts
> +import { ElewaVerticalIconAndTextComponent } from 'libs/features/components/cards/src/lib/cards/elewa-vertical-icon-and-text/elewa-vertical-icon-and-text.component';
Import from the aliased path, In your case you need to import the module that exports this component.

2023-02-24 06:13 UTC, IanOdhiambo9 requested changes

2023-02-24 06:13 UTC, IanOdhiambo9 commented on libs/pages/elewa/about-us/src/lib/components/about-us-we-care/about-us-we-care.component.html
> +        </div>
This issue was dependent on #14, it should therefore reuse that card.

2023-03-03 05:03 UTC, IanOdhiambo9 commented
Closing because no updates have been made here since changes were requested

2023-03-03 05:03 UTC, closed without merging