Footer
italanta/elewa-group pull request #272
Opened 2023-02-22 18:26 UTC by lilmithi

# Description

Worked on this in collaboration with @royokite 

Fixes #252

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

# Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-02-22 18:27 UTC, lilmithi commented
@IanOdhiambo9 , @LemmyMwaura awaiting review

2023-02-24 06:37 UTC, IanOdhiambo9 requested changes

2023-02-24 06:37 UTC, IanOdhiambo9 commented on libs/elements/layout/src/lib/pages/elewa-group-main-page/elewa-group-main-page.component.ts
> +    this.route = this.router.url;
This will return a full url and url will defer depending on language but is still same page i.e. home/en, home/fr and home/nl

2023-02-24 06:37 UTC, IanOdhiambo9 commented on libs/elements/layout/src/lib/pages/elewa-group-main-page/elewa-group-main-page.component.ts
> +    this.route = this.router.url;
The url needs to be split and fetch page by index

2023-02-24 06:37 UTC, IanOdhiambo9 commented on libs/elements/layout/src/lib/pages/elewa-group-main-page/elewa-group-main-page.component.html
> +      <div footer class="footer-content" *ngSwitchCase="'/contact/en'">
Missing a defaultCase

2023-02-24 06:37 UTC, IanOdhiambo9 commented on libs/elements/layout/src/lib/pages/elewa-group-main-page/elewa-group-main-page.component.html
> +      <div footer class="footer-content" *ngSwitchCase="'/home/en'">
Switch needs to be inside this class to avoid duplication this div multiple times or switching entire footer component.

2023-02-27 05:22 UTC, IanOdhiambo9 approved these changes

2023-02-27 05:22 UTC, merged