249/call to action
italanta/elewa-group pull request #286
Opened 2023-02-23 07:54 UTC by VinceXIV

# Description
Fixed issue #249 
Did the following to achieve this
1. Created a new component named CallToActionComponent
2. copied all the stuff in the original component to this one
3. Modified the HomePageJobsComponent to reuse this newly created component

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Screenshot (optional)
![Screenshot from 2023-02-22 15-35-47](https://user-images.githubusercontent.com/81687679/220621705-861c489a-bed7-4fab-a310-dbefc26334e2.png)
![Screenshot from 2023-02-22 15-35-17](https://user-images.githubusercontent.com/81687679/220621731-cb699932-c4e7-4d1b-b7cd-0255516bbb96.png)

# How Has This Been Tested?
Tried passing different values to the component at home page and seeing how it affects what is rendered. In the screenshot, what I changed was the text align property to see what it does to what is rendered. The others can be changed too

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2023-02-23 09:19 UTC, VinceXIV commented
Hello @IanOdhiambo9

2023-02-24 08:02 UTC, IanOdhiambo9 requested changes

2023-02-24 08:02 UTC, IanOdhiambo9 commented on libs/pages/elewa/home/src/lib/components/home-jobs-section/home-jobs-section.component.html
> +</elewa-group-call-to-action>
This should be moved to a shared lib like features/components/banners

2023-02-24 08:02 UTC, IanOdhiambo9 commented on libs/pages/elewa/home/src/lib/features-elewa-home.module.ts
> +    SocialImpactModule
Not allowed, page modules should not import each other. May cause circular dependency later on. Use shared libs.

2023-02-24 08:02 UTC, IanOdhiambo9 commented on libs/pages/elewa/social-impact/src/lib/components/call-to-action/call-to-action.component.html
> +</section>
Needs to be in a shared lib should be named elewa-group-call-to-action

2023-02-25 19:10 UTC, VinceXIV commented
Hey @IanOdhiambo9

2023-02-27 05:45 UTC, IanOdhiambo9 commented
This issue has been closed.

2023-02-27 05:45 UTC, closed without merging