Contact form
italanta/elewa-group pull request #341
Opened 2023-02-27 14:51 UTC by marcokumu

# Description

I worked on this issue #316 .
This contact form involved reusing the button component that had been created.

# Screenshot (optional)
![Screenshot from 2023-02-27 17-42-52](https://user-images.githubusercontent.com/90620737/221594598-e16b5bdf-22ae-4562-96bd-89206956a234.png)

# Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-02-27 14:55 UTC, marcokumu commented
@IanOdhiambo9 kindly review

2023-02-28 12:58 UTC, IanOdhiambo9 requested changes
Should match provided design

2023-02-28 12:58 UTC, IanOdhiambo9 commented on libs/pages/elewa/contact/src/lib/components/contact-form/contact-form.component.html
> +    <div class="icons">
Your design is great but still not quite there.
The anchor text for privacy policy is white not blue
The margin between input fields is not consistent
The width of the input fields is not consistent
No mobile design for responsiveness

2023-02-28 12:58 UTC, IanOdhiambo9 commented on libs/pages/elewa/contact/src/lib/components/contact-form/contact-form.component.ts
> +      message: '',
Move logic to a function "buildContactForm" and call function in ngOnInit

2023-02-28 12:58 UTC, IanOdhiambo9 commented on libs/pages/elewa/contact/src/lib/pages-elewa-contact.module.ts
> +import { ContactFormComponent } from './components/contact-form/contact-form.component';
order of imports is not correct

2023-02-28 12:58 UTC, IanOdhiambo9 commented on libs/pages/elewa/contact/src/lib/pages/contact-page/contact-page.component.html
> +<elewa-group-contact-form></elewa-group-contact-form>
add the main template page here

2023-03-03 05:18 UTC, IanOdhiambo9 commented
Closing because no updates made here.

2023-03-03 05:18 UTC, closed without merging