#317 Contact banner
italanta/elewa-group pull request #343
Opened 2023-02-27 15:16 UTC by timothymureithi

# Description

This is a contact form banner for the contact page. Based on the requirements it is a responsive form that adjusts its layout based on the screen size of the device being used. The banner consists of a centered title, "Contacts", followed by three input fields: "Questions", "Press", and "Phone".

Example
This pull request is part of the work to make it easier for people to contribute to naming convention guides. 
One of the easiest way to make small changes would be using the Edit on Github button.

To achieve this, we needed to:

```
- Import contact-banner to contact-page
- Create a title for the banner and also create 3 input fields
- Write CSS code to ensure that the component is responsive on all devices
```

Fixes # (issue) - *Example*: Fixes # ([S4Y-400](https://www.w3.org/Provider/Style/dummy.html), [S4Y-100](https://www.w3.org/Provider/Style/dummy.html))

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Screenshot (optional)
![Screenshot from 2023-02-27 18-09-08](https://user-images.githubusercontent.com/110177559/221602760-8540993c-551d-4e80-a4de-52350b014785.png)

![Screenshot from 2023-02-27 18-09-27](https://user-images.githubusercontent.com/110177559/221602793-a2778aba-751e-4419-a0ce-8342e1e0d6a7.png)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 
Please also list any relevant details for your test configuration if necessary.
- [ ] Test A
- [ ] Test B

**Test Configuration**: (optional)
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-02-27 15:18 UTC, timothymureithi commented
Created a new pull request under a new branch. I will close the other one after feedback.

2023-02-28 14:50 UTC, timothymureithi commented on libs/pages/elewa/contact/src/lib/components/contact-banner/contact-banner.component.html
> +      <label for="press">Press</label>
I'm fixing up the code now

2023-02-28 15:17 UTC, timothymureithi commented on libs/pages/elewa/contact/src/lib/components/contact-banner/contact-banner.component.html
> +      <label for="press">Press</label>
Updated the changes. Please review

2023-03-03 05:21 UTC, IanOdhiambo9 commented
On mobile the width of the inputs is not uniform.

2023-03-03 05:21 UTC, IanOdhiambo9 requested changes
On mobile the width of the inputs is not uniform.

2023-03-03 05:37 UTC, timothymureithi commented
> On mobile the width of the inputs is not uniform.

Let me fix it now.

2023-03-03 05:51 UTC, timothymureithi commented
Fixed. Please review

2023-03-06 11:34 UTC, merged