FEAT: added Venture Labs brand banner
italanta/elewa-group pull request #348
Opened 2023-02-27 16:52 UTC by 23po

# Description

Created Ventures Labs brand banner on brands page.

To achieve this,:

```
- I customized the reusable brands banner
```

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

# Screenshot (optional)
![venture labs](https://user-images.githubusercontent.com/48943229/221627750-fc68d8af-b3d9-45e8-9dda-67f014c3428b.png)

# How Has This Been Tested?

This runs on the development server

# Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-02-27 16:52 UTC, 23po commented
@IanOdhiambo9 please review

2023-02-28 13:16 UTC, IanOdhiambo9 requested changes
resolve conflicts

2023-02-28 13:16 UTC, IanOdhiambo9 commented on libs/pages/elewa/brands/src/lib/pages-elewa-brands.module.ts
>  import { BrandsRoutingModule } from './brands.routing';
order of imports

2023-02-28 14:25 UTC, 23po commented
@IanOdhiambo9 resolved

2023-03-03 05:39 UTC, IanOdhiambo9 commented
merged one of the same

2023-03-03 05:39 UTC, closed without merging