Careers vacancies
italanta/elewa-group pull request #353
Opened 2023-02-27 18:07 UTC by marcokumu

# Description

I worked on this issue #315 to create Vacancies list
![Screenshot from 2023-03-03 01-12-51](https://user-images.githubusercontent.com/90620737/222576403-90ffa3a9-16c7-4cf3-8e74-2b15974a96be.png)
![Screenshot from 2023-03-03 01-30-16](https://user-images.githubusercontent.com/90620737/222576705-54289565-55a0-41c4-b9c2-4d59943ce980.png)

# Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-02-27 18:12 UTC, marcokumu commented
@IanOdhiambo9 Kindly review

2023-02-28 13:28 UTC, IanOdhiambo9 requested changes
The list should utilise a loop *ngFor..

The widths are not similar, same for font weights.

2023-02-28 15:23 UTC, marcokumu commented
@IanOdhiambo9 I've made the requested changes.

2023-03-03 05:42 UTC, IanOdhiambo9 approved these changes

2023-03-03 05:44 UTC, merged