Elewa brands elewa education
italanta/elewa-group pull request #358
Opened 2023-02-27 21:29 UTC by mwanjiku56

# Description

I worked on this issue #322 

I reused a component solved on issue #321

# Screenshot (optional)
![Screenshot from 2023-02-28 00-09-40](https://user-images.githubusercontent.com/87025455/221689050-96df8765-94ed-4437-9e6c-def501c1bab9.png)

# Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-02-28 13:46 UTC, IanOdhiambo9 requested changes

2023-02-28 13:46 UTC, IanOdhiambo9 commented on libs/pages/elewa/brands/src/lib/pages-elewa-brands.module.ts
> +import { ElewaBrandsElewaEducationComponent } from './components/elewa-brands-elewa-education/elewa-brands-elewa-education.component';
order of imports

2023-03-01 07:41 UTC, mwanjiku56 commented on libs/pages/elewa/brands/src/lib/pages-elewa-brands.module.ts
> +import { ElewaBrandsElewaEducationComponent } from './components/elewa-brands-elewa-education/elewa-brands-elewa-education.component';
changes implemented

2023-03-03 05:55 UTC, IanOdhiambo9 commented
You can only do 2+ points

2023-03-03 05:55 UTC, closed without merging