Issue316/Contact Form
italanta/elewa-group pull request #397
Opened 2023-03-03 12:56 UTC by George-Onyango

# Description

This pull request create a new contact form that a user is able to fill in order to get into contact with customers that might have reviews on the organization

Fixes # (issue) - (#316 )

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# Screenshot (optional)

# Web

![Screenshot from 2023-03-03 15-53-28](https://user-images.githubusercontent.com/69570282/222725224-ccf52115-482e-4d02-9c3f-8bb0d63a2957.png)

# Mobile

![Screenshot from 2023-03-03 15-53-36](https://user-images.githubusercontent.com/69570282/222725282-7120f9db-4c57-4863-bb11-dc0d05a2ecbf.png)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 
Please also list any relevant details for your test configuration if necessary.
- [x] Test responsiveness on design change

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2023-03-03 13:03 UTC, George-Onyango commented
@IanOdhiambo9  requesting review

2023-03-06 11:41 UTC, IanOdhiambo9 requested changes

2023-03-06 11:41 UTC, IanOdhiambo9 commented on libs/pages/elewa/contact/src/lib/components/contact-banner/contact-banner.component.html
> +      <p class="text">{{pressEmail}}</p>
This was not part of this issue

2023-03-06 11:41 UTC, IanOdhiambo9 commented
The icon on the dropdown is not vertically centered on the field

2023-03-08 05:13 UTC, IanOdhiambo9 commented
This issue has been completed

2023-03-08 05:13 UTC, closed without merging