#443:feat:news-page
italanta/elewa-group pull request #466
Opened 2023-03-10 20:29 UTC by yegobaroni

# Description

This pull request works on issue #443 which reuses issue #411

Fixes # 443

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

# Screenshot (optional)
![Screen Shot 2023-03-10 at 10 35 58 PM](https://user-images.githubusercontent.com/89794664/224419764-a45c5677-bd50-4288-8d36-cf3198d65088.png)

mobile

![Screen Shot 2023-03-10 at 10 36 19 PM](https://user-images.githubusercontent.com/89794664/224420046-aba68b8d-a2d5-4e45-a3a7-57c3b424b387.png)

# Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-03-23 07:25 UTC, IanOdhiambo9 requested changes
Your fonts and font sizes are not as provided on the design. Please check

2023-03-23 07:25 UTC, IanOdhiambo9 commented on libs/features/components/ui-lists/src/lib/elewa-group-article-list/elewa-group-article-list.component.ts
> +
Move this to an interface file in the same lib models/articles.interface.ts

2023-03-23 07:25 UTC, IanOdhiambo9 commented on libs/pages/elewa/news/src/lib/components/elewa-news-section/elewa-news-section.component.html
> +      <a class="elewa-news-section-item" (click)="selectedTab='press'; filterArticles();" [class.active]="selectedTab==='press'">Press</a>
use a loop and make this a button

2023-03-23 07:27 UTC, IanOdhiambo9 commented
The tabs should remain tabs on mobile. Just make them a grid of 2 x 2

2023-03-25 19:13 UTC, yegobaroni commented
@IanOdhiambo9 changes made. kindly review.

2023-04-14 04:43 UTC, closed without merging