Pauline
italanta/elewa-group pull request #467
Opened 2023-03-11 10:54 UTC by pauleen123

# Description

This pull request is part of the work to create the news section page where a user can view and filter different articles.

To achieve this, we needed to:

- Re-use issue #411 
- Create a filter function that filters through the tabs for specific news
- 
Fixes #443 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Screenshot (optional)
large screen view for the all news tab
![largescreenview](https://user-images.githubusercontent.com/106158118/224479835-94133705-da4e-4625-9cc2-a3394b19cfa4.png)

large screen view on the elewa tab
![largeviewonelewatab](https://user-images.githubusercontent.com/106158118/224479846-1bb7f4c9-9e4b-4eb6-aeeb-4cbf2103b560.png)

mobile view on the all news tab
![mobileview1](https://user-images.githubusercontent.com/106158118/224479853-8d501fee-c91f-45d1-881b-126f95caeac4.png)

mobile view on the i-talanta tab
![mobileview2](https://user-images.githubusercontent.com/106158118/224479859-77e59ce8-9dfb-4488-b95e-e7dbb1dbf26f.png)

# Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

2023-03-11 10:57 UTC, pauleen123 commented
hey @IanOdhiambo9 kindly review my pull reques on this issue

2023-03-23 07:30 UTC, IanOdhiambo9 requested changes

2023-03-23 07:30 UTC, IanOdhiambo9 commented on libs/features/components/ui-lists/src/lib/elewa-group-article-list/elewa-group-article-list.component.ts
> +export interface Article { image: string; timestamp: string; title: string; body: string; topic: string;} //import this interface in the component you will be reusing article-list in. e.g import { Ar
Move interface to an interface file inside this lib. models/article.interface.ts

2023-03-23 07:30 UTC, IanOdhiambo9 commented on libs/pages/elewa/news/src/lib/components/elewa-news-section/elewa-news-section.component.html
> +    </nav>
No need for nav, use a loop here and make this a button

2023-03-23 07:31 UTC, IanOdhiambo9 commented
Why is this identical to https://github.com/italanta/elewa-group/pull/466 ??

2023-03-30 09:55 UTC, pauleen123 commented
hey @IanOdhiambo9 kindly review my updated PR as per the requested changes

2023-04-14 04:43 UTC, closed without merging