Feature job section#13
italanta/elewa-group pull request #67
Opened 2023-02-08 06:57 UTC by EliusCaleb

The task to design :
A feature that is a stand-alone component. This page should be different from the element.

The text "open opportunities" is an anchor link that points to the /jobs page

To achieve this, we needed to:
  1) We need to create a standalone component  that is called job-section
 2) Add view to the components  which is HTML code
 3)Add style to the component
4) Render this component to the app component 

## Type of change
Delete my package.lock json

# Screenshot (optional)
![image](https://user-images.githubusercontent.com/109586789/217456552-2eec2fe6-5339-4041-ba22-27c32ad5a041.png)

# How Has This Been Tested?
When I click the open or opportunities it redirects to /jobs

# Checklist:
- [ 1] My code follows the style guidelines of this project
- [2 ] I have performed a self-review of my code
- [3 ] I have made corresponding changes to the documentation
- [ 4] Any dependent changes have been merged and published in downstream modules

2023-02-08 07:06 UTC, IanOdhiambo9 requested changes
You've also pushed your package.json files.

This cannot be merged.

2023-02-08 07:06 UTC, IanOdhiambo9 commented on apps/elewa-group-website/src/app/app.component.html
> + <elewa-group-job-section></elewa-group-job-section
Job section needs to be on the home page.
only home page tag should be on thing file..

2023-02-08 07:06 UTC, IanOdhiambo9 commented on libs/pages/elewa/home/src/lib/pages/home-page/home-page.component.ts
> +export class HomePageComponent {}
This entire component needs to be inside a components folder on this lib..

Sync your fork, the components folder was already created.

2023-02-08 07:07 UTC, IanOdhiambo9 requested changes

2023-02-08 07:07 UTC, IanOdhiambo9 commented on apps/elewa-group-website/src/main.ts
> +// bootstrapApplication(AppComponent)
No need to change this file, keep as it was

2023-02-08 07:07 UTC, IanOdhiambo9 commented on apps/elewa-group-website/src/app/app.module.ts
>    ],
No need to change this file.

2023-02-08 07:50 UTC, EliusCaleb commented
I have change the  job-section

2023-02-10 05:47 UTC, IanOdhiambo9 commented
Hello
I'm closing this pull request to to high number of conflicts not resolved.

2023-02-10 06:01 UTC, IanOdhiambo9 commented
Hello
I'm closing this pull request to to high number of conflicts not resolved and you've deleted the package.json and lock files. This will cause deletion on main branch as well. Please do a new PR without this files.

2023-02-10 06:01 UTC, closed without merging