#31 Create reusable text and image banner (side by side)
italanta/elewa-group pull request #91
Opened 2023-02-09 16:31 UTC by lilmithi

# Description
This has been built in collaboration with @royokite 

- We have designed a reusable text and image banner in which the image and text render according to the side specified with the default set to 'left'(image on the left, text on the right')
- The component accepts a title, text, image url, background color and placement('left' or 'right')

Fixes #31  

## Type of change

Please delete options that are not relevant.
- [x] New feature (non-breaking change which adds functionality)

# Screenshot
White background (Image left) Desktop
![leftwhitedesktop](https://user-images.githubusercontent.com/104300169/217760731-e2269945-c905-4968-8099-05d5a8406357.png)

White background (Image right) Desktop
![rightwhitedesktop](https://user-images.githubusercontent.com/104300169/217760829-dc5ee24a-fb2c-48f8-9f05-322848bfa6a3.png)

White background (Image right) Mobile
![rightwhitemobile](https://user-images.githubusercontent.com/104300169/217760995-78f6bdbd-d362-4285-893e-4fa2dcf72348.png)

White background (Image left) Mobile
![leftwhitemobile](https://user-images.githubusercontent.com/104300169/217761284-94728fcd-c9d1-47c2-acea-504af9a277c6.png)

Black background (Image left) Desktop
![leftblackdesktop](https://user-images.githubusercontent.com/104300169/217761398-dfd36e97-552d-436c-acfc-2ca8063f6fb0.png)

Black background (Image right) Desktop
![rightblackdesktop](https://user-images.githubusercontent.com/104300169/217761522-d9835605-5609-4a4e-a8a9-5661e58ee2b4.png)

Black background (Image right) Mobile
![rightblackmobile](https://user-images.githubusercontent.com/104300169/217761637-df9b5d43-28d8-4d85-9e64-aeb8761e86ea.png)

Black background (Image left) Mobile
![leftblackmobile](https://user-images.githubusercontent.com/104300169/217762118-071bc20b-6737-4d28-a62f-7b96df75fdeb.png)

# How Has This Been Tested?

- [x] Tested with different browsers for any breaking changes

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2023-02-09 16:32 UTC, lilmithi commented
@IanOdhiambo9 awaiting your review

2023-02-10 07:24 UTC, IanOdhiambo9 requested changes
Good Job on this but the component was put in the wrong place. Please move to  libs/features/components/banners as instructed on the issue template

2023-02-10 07:24 UTC, IanOdhiambo9 commented on libs/elements/layout/src/lib/components/banners/elewa-group-image-and-text-banner/elewa-group-image-and-text-banner.component.html
> +>
use *ngIf="placement == 'right'; else  'imageLeft'"

and put and #imageLeft tag on an ng-template

2023-02-10 07:25 UTC, IanOdhiambo9 commented
Do PR to staging branch

2023-02-10 08:31 UTC, closed without merging