#41  Create team members carousel
italanta/elewa-group pull request #94
Opened 2023-02-09 16:54 UTC by lilmithi

# Description

This component has been done in collaboration with @royokite 
- We have managed to create a responsive carousel following the design outlined

Fixes #41 

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

# Screenshot
Desktop view
![teamdesktop](https://user-images.githubusercontent.com/104300169/217881811-86ac10d4-a447-425c-96ae-149d24f62445.png)

Mobile view
![carouselmobile](https://user-images.githubusercontent.com/104300169/217881911-3f015777-b344-4f77-88ae-2cd97ac6a2a9.png)

# How Has This Been Tested?
- [ ] Tested against different browsers for breaking changes

# Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings

2023-02-09 16:54 UTC, lilmithi commented
@IanOdhiambo9 awaiting review

2023-02-10 07:32 UTC, IanOdhiambo9 requested changes

2023-02-10 07:32 UTC, IanOdhiambo9 commented on libs/pages/elewa/about-us/src/lib/team-members/membersInterface.ts
> +    imageLink:
Move members interface to libs/model/elewa (package)

name file elewa-team-members.interface.ts

export this file on this index.ts of this library for reuse in other places like this issue.

2023-02-10 07:32 UTC, IanOdhiambo9 commented on libs/pages/elewa/about-us/src/lib/team-members/team-members.component.html
> +          src="{{ member.imageLink }}"
use [src]="member.imageLink" instead of src="{{ member.imageLink }}"

do the same for all image src tags here.

2023-02-10 07:32 UTC, IanOdhiambo9 commented on libs/pages/elewa/about-us/src/lib/team-members/team-members.component.ts
> +import { Members } from './membersInterface';
use interface from libs/model/elewa

2023-02-10 07:32 UTC, IanOdhiambo9 commented
Do PR to staging branch

2023-02-10 08:29 UTC, closed without merging